name: Release

# Run workflow on commits to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install GPG
        run: brew install gnupg

      ## IMPORTANT: this creates the 'build' installation folder and must be the FIRST action!
      ## Deploy in Maven repository
      - name: Copy GPG Private key
        run: echo "${{ secrets.gpg_private_key }}" > private-key.txt && gpg --import --no-tty --batch --yes private-key.txt
      - name: Deploy to Maven Central respository
        env:
          MAVEN_NEXUS_USER: ${{ secrets.nexus_username }}
          MAVEN_NEXUS_PASSWORD: ${{ secrets.nexus_password }}
        run: mvn clean deploy -Dgpg.passphrase=${{ secrets.gpg_passphrase }} -DskipTests  -P deploy

